parameters:
- name: manifestPath
  default: Packages.psd1

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Packages.psd1

variables: 
  - group: RPackageVariableGroup

stages:
  - stage: Update
    jobs:
    - job: Update
      steps:
      - checkout: self
      - task: DownloadSecureFile@1
        name: DownloadPfx
        inputs:
          secureFile: 'CodeSigningCertificate.pfx'
      - pwsh: '$(Build.SourcesDirectory)/Update.ps1 `
                      -ManifestPath ''$(Build.SourcesDirectory)/${{ parameters.manifestPath }}'' `
                      -OutputPath ''$(Build.ArtifactStagingDirectory)'' `
                      -CertificateSecret ''$(certificateSecret)'' `
                      -CertificatePath $(DownloadPfx.secureFilePath)'
        displayName: 'Update repository'
      - task: AzureCLI@2
        displayName: Blob Copy
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: ps
          scriptLocation: inlineScript
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az account set --subscription $(subscriptionName)
            az storage fs directory upload -f '$web' --account-name $(storageAccountName) -s "$(Build.ArtifactStagingDirectory)/*" -d "$(storageAccountDir)" --recursive --subscription $(subscriptionName)
      - publish: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Publish Output'
        artifact: Repository